version: '3.7'

services:

  gateway:
    build:
      context: ./services/gateway
    ports:
      - 80:80

  backend:
    build:
      context: ./services/backend
    volumes:
      - ./services/backend/src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
      - ./exports:/usr/src/app/exports
    ports:
      - 8000:8000 # No need to expose
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend/src:/usr/src/app/src
    ports:
      - 3000:3000 # No need to expose
      - 35729:35729
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    build:
      context: ./services/postgres
    volumes:
      - ./services/postgres/data:/var/lib/postgresql
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  flyway:
    build:
      context: ./services/postgres/flyway
    volumes:
      - ./services/postgres/flyway/migrations:/flyway/sql
    entrypoint: /bin/wait-for-it.sh postgres:5432 -- flyway migrate
    links:
      - postgres
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
      - FLYWAY_SCHEMAS=apidata
      - FLYWAY_BASELINE_VERSION=0
      - FLYWAY_BASELINE_ON_MIGRATE=true

  analyzer:
    build:
      context: ./services/analyzer
    volumes:
      - ./services/analyzer:/usr/src/app
      - ./uploads:/usr/src/app/uploads
      - ./exports:/usr/src/app/exports
    ports:
      - 8080:8080
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8