/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-10-28 16:33:48 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@postgres/postgres -t samplepack -t sample -t samplepack_has_sample -t sample_has_tag -t tag -s public
 *
 */


export namespace samplepackFields {
    export type id = number;
    export type name = string | null;
    export type created_at = Date | null;

}

export interface samplepack {
    id: samplepackFields.id;
    name: samplepackFields.name;
    created_at: samplepackFields.created_at;

}

export namespace sampleFields {
    export type id = number;
    export type md5 = string | null;
    export type filename = string | null;
    export type metadata = Object | null;
    export type bpm = number | null;
    export type location = Object | null;
    export type created_at = Date | null;

}

export interface sample {
    id: sampleFields.id;
    md5: sampleFields.md5;
    filename: sampleFields.filename;
    metadata: sampleFields.metadata;
    bpm: sampleFields.bpm;
    location: sampleFields.location;
    created_at: sampleFields.created_at;

}

export namespace samplepack_has_sampleFields {
    export type pack_id = number;
    export type sample_id = number;

}

export interface samplepack_has_sample {
    pack_id: samplepack_has_sampleFields.pack_id;
    sample_id: samplepack_has_sampleFields.sample_id;

}

export namespace sample_has_tagFields {
    export type sample_id = number;
    export type tag_id = number;

}

export interface sample_has_tag {
    sample_id: sample_has_tagFields.sample_id;
    tag_id: sample_has_tagFields.tag_id;

}

export namespace tagFields {
    export type id = number;
    export type name = string | null;
    export type description = string | null;

}

export interface tag {
    id: tagFields.id;
    name: tagFields.name;
    description: tagFields.description;

}
