/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-10-27 00:17:18 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@postgres/postgres -t sample -t sample_has_tag -t tag -s public
 *
 */


export namespace sampleFields {
    export type id = number;
    export type md5 = string | null;
    export type filename = string | null;
    export type metadata = Object | null;
    export type bpm = number | null;
    export type location = Object | null;

}

export interface sample {
    id: sampleFields.id;
    md5: sampleFields.md5;
    filename: sampleFields.filename;
    metadata: sampleFields.metadata;
    bpm: sampleFields.bpm;
    location: sampleFields.location;

}

export namespace sample_has_tagFields {
    export type sample_id = number;
    export type tag_id = number;

}

export interface sample_has_tag {
    sample_id: sample_has_tagFields.sample_id;
    tag_id: sample_has_tagFields.tag_id;

}

export namespace tagFields {
    export type id = number;
    export type name = string | null;
    export type description = string | null;

}

export interface tag {
    id: tagFields.id;
    name: tagFields.name;
    description: tagFields.description;

}
